import {
  Activity,
  Apple,
  BatteryLow,
  BatteryMedium,
  Bed,
  Bike,
  Brain,
  Check,
  Circle,
  CircleAlert,
  CircleDotDashed,
  CloudSun,
  Coffee,
  Droplet,
  Droplets,
  Dumbbell,
  Flame,
  Footprints,
  Frown,
  Heart,
  HeartCrack,
  HeartPulse,
  Leaf,
  MapPin,
  Moon,
  Pill,
  Search,
  ShieldCheck,
  ShieldOff,
  Smile,
  Sparkles,
  Sun,
  TestTube2,
  Thermometer,
  Timer,
  Waves,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { createElement } from "react";

export type SymptomGroupTone = "physical" | "digestion" | "discharge" | "energy" | "intimacy" | "lifestyle" | "tests";
export type SymptomUiTone = "pink" | "purple" | "orange" | "green" | "blue";

export type SymptomGroup = {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
  tone: SymptomGroupTone;
  uiTone: SymptomUiTone;
  options: string[];
};

export const symptomGroups: SymptomGroup[] = [
  {
    id: "symptoms",
    title: "Боль и самочувствие",
    description: "Боль, температура и физические ощущения",
    icon: HeartPulse,
    tone: "physical",
    uiTone: "pink",
    options: ["Всё в порядке", "Спазмы", "Головная боль", "Мигрень", "Головокружение", "Усталость", "Чувствительная грудь", "Боль в спине", "Боль внизу живота", "Боль в суставах", "Боль в мышцах", "Отёки", "Приливы жара", "Озноб", "Ночная потливость", "Бессонница", "Забывчивость"],
  },
  {
    id: "digestion",
    title: "Пищеварение и стул",
    description: "Живот, аппетит и изменения пищеварения",
    icon: Leaf,
    tone: "digestion",
    uiTone: "green",
    options: ["Без изменений", "Вздутие", "Тошнота", "Рвота", "Запор", "Диарея", "Газообразование", "Боль в животе", "Изжога", "Тяга к сладкому", "Повышенный аппетит", "Сниженный аппетит"],
  },
  {
    id: "discharge",
    title: "Выделения и комфорт",
    description: "Характер выделений, сухость, зуд или жжение",
    icon: Waves,
    tone: "discharge",
    uiTone: "purple",
    options: ["Выделений нет", "Кремообразные", "Водянистые", "Липкие", "Слизистые", "Кровомажущие", "Нетипичные", "Белые комковатые", "Серые", "С неприятным запахом", "Зуд во влагалище", "Жжение", "Сухость во влагалище"],
  },
  {
    id: "energy",
    title: "Настроение и энергия",
    description: "Эмоциональный фон, ресурс и концентрация",
    icon: BatteryMedium,
    tone: "energy",
    uiTone: "orange",
    options: ["Высокая энергия", "Нормальная энергия", "Мало энергии", "Спокойствие", "Радость", "Стресс", "Тревога", "Раздражительность", "Апатия", "Перепады настроения", "Подавленность", "Плаксивость", "Навязчивые мысли", "Сложно сосредоточиться", "Нет мотивации"],
  },
  {
    id: "skin",
    title: "Кожа и волосы",
    description: "Изменения кожи, волос и внешнего самочувствия",
    icon: Sparkles,
    tone: "physical",
    uiTone: "pink",
    options: ["Прыщи", "Жирная кожа", "Сухая кожа", "Чувствительная кожа", "Выпадение волос", "Жирные волосы", "Сухие волосы"],
  },
  {
    id: "intimacy",
    title: "Интимная жизнь",
    description: "Приватная отметка, не включается в отчёт автоматически",
    icon: Heart,
    tone: "intimacy",
    uiTone: "pink",
    options: ["Секса не было", "Секс с защитой", "Секс без защиты", "Комфортно", "Сухость", "Боль во время секса", "Кровь после секса"],
  },
  {
    id: "lifestyle",
    title: "Активность и события",
    description: "Движение, отдых и события, которые важно помнить",
    icon: Activity,
    tone: "lifestyle",
    uiTone: "green",
    options: ["Без тренировки", "Ходьба", "Растяжка", "Йога", "Тренировка", "Бег", "Плавание", "Велосипед", "Аэробика или танцы", "Командный спорт", "Высокая нагрузка", "Отдых", "Медитация", "Дыхательные упражнения", "Ведение дневника", "Алкоголь", "Путешествие", "Болезнь или травма"],
  },
  {
    id: "contraception",
    title: "Контрацепция",
    description: "Метод, приём по плану и важные изменения",
    icon: ShieldCheck,
    tone: "lifestyle",
    uiTone: "blue",
    options: ["Таблетки", "Кольцо", "Пластырь", "ВМС", "Имплант", "Инъекция", "Презерватив", "Другой метод", "Принято вовремя", "Пропуск", "Смена метода", "Отмена"],
  },
  {
    id: "tests",
    title: "Домашние тесты",
    description: "Сохраняйте только фактический результат теста",
    icon: TestTube2,
    tone: "tests",
    uiTone: "purple",
    options: ["Тест на беременность: отрицательный", "Тест на беременность: положительный", "Тест на овуляцию: отрицательный", "Тест на овуляцию: положительный", "Измерена базальная температура"],
  },
];

const exactIcons: Record<string, LucideIcon> = {
  "Всё в порядке": Check,
  "Без изменений": Check,
  "Выделений нет": X,
  "Спазмы": Activity,
  "Головная боль": Brain,
  "Мигрень": Brain,
  "Головокружение": CircleDotDashed,
  "Усталость": BatteryLow,
  "Чувствительная грудь": HeartPulse,
  "Боль в спине": Activity,
  "Боль внизу живота": CircleDotDashed,
  "Боль в суставах": Activity,
  "Боль в мышцах": Dumbbell,
  "Отёки": Droplets,
  "Приливы жара": Flame,
  "Озноб": CloudSun,
  "Ночная потливость": Moon,
  "Бессонница": Bed,
  "Забывчивость": Brain,
  "Вздутие": CircleDotDashed,
  "Тошнота": Waves,
  "Рвота": Waves,
  "Запор": Circle,
  "Диарея": Activity,
  "Газообразование": Wind,
  "Боль в животе": CircleAlert,
  "Изжога": Flame,
  "Тяга к сладкому": Apple,
  "Повышенный аппетит": Apple,
  "Сниженный аппетит": Apple,
  "Кремообразные": Droplet,
  "Водянистые": Droplets,
  "Липкие": Droplet,
  "Слизистые": Waves,
  "Кровомажущие": Droplet,
  "Нетипичные": CircleAlert,
  "Белые комковатые": CircleDotDashed,
  "Серые": Droplets,
  "С неприятным запахом": Wind,
  "Зуд во влагалище": CircleAlert,
  "Жжение": Flame,
  "Сухость во влагалище": Droplets,
  "Высокая энергия": Zap,
  "Нормальная энергия": BatteryMedium,
  "Мало энергии": BatteryLow,
  "Спокойствие": Smile,
  "Радость": Smile,
  "Тяжело": Frown,
  "Спокойно": Smile,
  "Хорошо": Smile,
  "Стресс": Zap,
  "Тревога": CircleAlert,
  "Раздражительность": Frown,
  "Апатия": BatteryLow,
  "Перепады настроения": CloudSun,
  "Подавленность": Frown,
  "Плаксивость": Droplet,
  "Навязчивые мысли": Brain,
  "Сложно сосредоточиться": Search,
  "Нет мотивации": BatteryLow,
  "Прыщи": CircleDotDashed,
  "Жирная кожа": Droplet,
  "Сухая кожа": Sun,
  "Чувствительная кожа": Sparkles,
  "Выпадение волос": Waves,
  "Жирные волосы": Droplet,
  "Сухие волосы": Sun,
  "Секса не было": X,
  "Секс с защитой": ShieldCheck,
  "Секс без защиты": ShieldOff,
  "Комфортно": Heart,
  "Сухость": Droplets,
  "Боль во время секса": HeartCrack,
  "Кровь после секса": Droplet,
  "Без тренировки": Bed,
  "Ходьба": Footprints,
  "Растяжка": Activity,
  "Йога": Activity,
  "Тренировка": Dumbbell,
  "Бег": Footprints,
  "Плавание": Waves,
  "Велосипед": Bike,
  "Аэробика или танцы": Activity,
  "Командный спорт": Activity,
  "Высокая нагрузка": Zap,
  "Отдых": Bed,
  "Медитация": Sparkles,
  "Дыхательные упражнения": Wind,
  "Ведение дневника": Heart,
  "Алкоголь": Coffee,
  "Путешествие": MapPin,
  "Болезнь или травма": CircleAlert,
  "Таблетки": Pill,
  "Кольцо": Circle,
  "Пластырь": Check,
  "ВМС": ShieldCheck,
  "Имплант": ShieldCheck,
  "Инъекция": Droplet,
  "Презерватив": ShieldCheck,
  "Другой метод": Circle,
  "Принято вовремя": Timer,
  "Пропуск": CircleAlert,
  "Смена метода": Activity,
  "Отмена": X,
  "Тест на беременность: отрицательный": X,
  "Тест на беременность: положительный": Check,
  "Тест на овуляцию: отрицательный": X,
  "Тест на овуляцию: положительный": Check,
  "Измерена базальная температура": Thermometer,
};

export function symptomIconFor(label: string): LucideIcon {
  return exactIcons[label] ?? Circle;
}

export function SymptomIcon({ label, strokeWidth = 1.8 }: { label: string; strokeWidth?: number }) {
  return createElement(symptomIconFor(label), { "aria-hidden": true, strokeWidth });
}
